[develop]: Updated ConfigWorkflow.rst to reflect changes to config_defaults.yaml (PI12)
ufs-community/ufs-srweather-app pull request #1095
Opened 2024-06-13 19:14 UTC by jdkublnick

## DESCRIPTION OF CHANGES: 
- Updated ConfigWorkflow.rst to reflect recent changes to config_defaults.yaml in order to keep documentation up to date.

### Type of change
- [X ] This change requires a documentation update

## TESTS CONDUCTED: 
None required for documentation. The docs build successfully on my fork and can be viewed at: https://ufs-srweather-app-joshua-kublnick.readthedocs.io/en/text-us-283/UsersGuide/index.html

## DEPENDENCIES:
N/A

## DOCUMENTATION:
All documentation

## ISSUE: 
Issue #1094 
## CHECKLIST

- [X ] My code follows the style guidelines in the Contributor's Guide
- [X ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ X] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [X ] documentation

## CONTRIBUTORS (optional): 
@gspetro-NOAA

2024-06-18 19:57 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``SENDECF_default``: (Default: NO)
```suggestion
``SENDECF_default``: (Default: "NO")
```

2024-06-18 19:57 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``SENDDBN_default``: (Default: NO)
```suggestion
``SENDDBN_default``: (Default: "NO")
```

2024-06-18 19:57 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``SENDDBN_NTC_default``: (Default: NO)
```suggestion
``SENDDBN_NTC_default``: (Default: "NO")
```

2024-06-18 19:57 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``SENDCOM_default``: (Default: YES)
```suggestion
``SENDCOM_default``: (Default: "YES")
```

2024-06-18 19:58 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``SENDWEB_default``: (Default: NO)
```suggestion
``SENDWEB_default``: (Default: "NO")
```

2024-06-18 19:58 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``KEEPDATA_default``: (Default: YES)
```suggestion
``KEEPDATA_default``: (Default: "YES")
```

2024-06-18 20:15 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   The number of nodes to request from the job scheduler for the nexus emission task.
```suggestion
   The number of nodes to request from the job scheduler for the NEXUS emission task.
```

2024-06-18 20:16 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``PT_SRC_SUBDIR``: (Default: ``NEI2016v1/v2023-01-PT``)
```suggestion
``PT_SRC_SUBDIR``: (Default: ``"NEI2016v1/v2023-01-PT"``)
```

2024-06-18 20:17 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   Sub-directory structure of point source data under FIXemis.
```suggestion
   Sub-directory structure of point source data under ``FIXemis``.
```

2024-06-18 20:24 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``COMINfire_default``:(Default: "")
```suggestion
``COMINfire_default``: (Default: "")
```

2024-06-20 14:25 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``COMINairnow_default``: (Default: "/path/to/airnow/obaservation/data")
```suggestion
``COMINairnow_default``: (Default: "/path/to/airnow/observation/data")
```

2024-06-20 14:27 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   User-defined path to the com type directories (OPSROOT=$PTMP/$envir).
```suggestion
   User-defined path to the com type directories (``OPSROOT=$PTMP/$envir``).
```

2024-06-20 14:33 UTC, gspetro-NOAA commented
@jdkublnick Could you change the line that says:
```
``KMP_AFFINITY_BIAS_CORRECTION_O3``: "scatter"
```
to:
```
``KMP_AFFINITY_BIAS_CORRECTION_O3``: (Default: "scatter")
```
I can't comment directly on the code since it hasn't been altered in this PR.

2024-06-20 14:47 UTC, gspetro-NOAA approved these changes
Looks good! @jdkublnick addressed all my feedback.

2024-06-20 15:10 UTC, MichaelLueken requested changes
@jdkublnick -

Overall, these changes look good!

I did note a minor difference with `PTMP` (rather than `PTMP_default`) and the default being `'{{ workflow.EXPT_BASEDIR }}/../nco_dirs'`.

2024-06-20 15:10 UTC, MichaelLueken commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``PTMP_default``: (Default "")
Should `PTMP_default` just be `PTMP` and should the default be `'{{ workflow.EXPT_BASEDIR }}/../nco_dirs'`, rather than empty?

```suggestion
``PTMP``: (Default ``'{{ workflow.EXPT_BASEDIR }}/../nco_dirs'``)
```

2024-06-20 15:36 UTC, jdkublnick commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``PTMP_default``: (Default "")
Yes, you are right.

2024-06-20 15:58 UTC, MichaelLueken approved these changes
Thanks, @jdkublnick!

Approving now.

2024-06-20 16:26 UTC, gspetro-NOAA commented
@jdkublnick I also just realized that maybe the default value for `CCPP_PHYS_DIR` should be updated to `'{{ [user.UFS_WTHR_MDL_DIR, "FV3", "ccpp", "physics", "physics", "SFC_Models", "Land", "Noahmp"] |path_join }}'`?

2024-06-20 16:49 UTC, jdkublnick commented
> @jdkublnick I also just realized that maybe the default value for `CCPP_PHYS_DIR` should be updated to `'{{ [user.UFS_WTHR_MDL_DIR, "FV3", "ccpp", "physics", "physics", "SFC_Models", "Land", "Noahmp"] |path_join }}'`?

Updated

2024-06-21 15:07 UTC, merged