[develop]: Updated ConfigWorkflow.rst to reflect changes to config_defaults.yaml (PI13)
ufs-community/ufs-srweather-app pull request #1133
Opened 2024-09-12 20:45 UTC by jdkublnick

DESCRIPTION OF CHANGES:
Updated ConfigWorkflow.rst to reflect recent changes to config_defaults.yaml in order to keep documentation up to date.
Type of change
[X ] This change requires a documentation update
TESTS CONDUCTED:
None required for documentation. The docs build successfully on my fork and can be viewed at: https://ufs-srweather-app-joshua-kublnick.readthedocs.io/en/text-us-336/BackgroundInfo/index.html
DEPENDENCIES:
N/A

DOCUMENTATION:
All documentation

ISSUE:
Issue https://github.com/ufs-community/ufs-srweather-app/issues/1132

CHECKLIST
[X ] My code follows the style guidelines in the Contributor's Guide
[X ] I have performed a self-review of my own code using the Code Reviewer's Guide
 I have commented my code, particularly in hard-to-understand areas
[X ] My changes need updates to the documentation. I have made corresponding changes to the documentation
 My changes do not require updates to the documentation (explain).
[X ] My changes generate no new warnings
 New and existing tests pass with my changes
[ X] Any dependent changes have been merged and published
LABELS (optional):
A Code Manager needs to add the following labels to this PR:

[X ] documentation

2024-09-13 14:04 UTC, MichaelLueken requested changes
@jdkublnick -

Thanks for going through the `ConfigWorkflow.rst` documentation and updating the entries that have been updated in `config_defaults.yaml`!

Cross referencing the changes that you have made in this PR with what is currently in the `ConfigWorkflow.rst` file at the HEAD of the develop branch, it looks like several of these entries are currently in the documentation.  Looking at the commit history for your `text/us-336` branch, it looks like the branch was created from a February 21, 2024 hash, with no other syncing with the develop branch after it was created.

Please merge the authoritative develop branch back into your `text/us-336` branch.  If you have any questions or require assistance, please let me know.

@gspetro-NOAA - While looking through the `ConfigWorkflow.rst` file and `config_defaults.yaml`, specifically in the `FIX*` sections, there is a disconnect occurring.  In `ConfigWorkflow.rst`, the definition of variables is `path to system directory`, while in `config_defaults.yaml`, it is `system directory where`.

Should the definitions be updated in either the `ConfigWorkflow.rst` or `config_defaults.yaml` files (and which file should be updated, if you think it should), or do you feel that the differences for the `FIX*` variables are fine as is?

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +  The run command for the AQM NEXUS tasks.
This is already present in `ConfigWorkflow.rst` at the HEAD of develop.

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   System directory where AQM emission data files are located.
Both of these entries are already present in `ConfigWorkflow.rst` at the HEAD of develop

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +  Name of a template file that contains information about the various UFS components and their run sequence (ufs-weather-model: ufs.configure). Its default value is the name of the file that the ufs
This is already present in `ConfigWorkflow.rst` at the HEAD of develop.  This configuration replaces the `NEMS_CONFIG_FN` option above.

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   Path to the ``UFS_CONFIG_FN`` file.
This is already present in `ConfigWorkflow.rst` at the HEAD of develop. This configuration replaces the `NEMS_CONFIG_TMPL_FP` option above.

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   Path to the ``UFS_CONFIG_FN`` file in the experiment directory.
This is already present in `ConfigWorkflow.rst` at the HEAD of develop. This configuration replaces the `NEMS_CONFIG_FP` option above.

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   Name of the experiment configuration file. It contains the primary experiment variables defined in this default configuration script and in the user-specified configuration as well as secondary ex
This is already present in `ConfigWorkflow.rst` at the HEAD of develop

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``CCPP_PHYS_DIR``: (Default: ``'{{ [user.UFS_WTHR_MDL_DIR, "FV3", "ccpp", "physics", "physics", "SFC_models", "Land", "Noahmp"] |path_join }}'``)
This is already present in `ConfigWorkflow.rst` at the HEAD of develop

2024-09-13 14:04 UTC, MichaelLueken commented on doc/UsersGuide/source/CustomizingTheWorkflow/ConfigWorkflow.rst
> +``FIELD_DICT_FN``: (Default: "fd_ufs.yaml")
This is already present in `ConfigWorkflow.rst` at the HEAD of develop

2024-09-13 14:48 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +
```suggestion
```

2024-09-13 14:48 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +>>>>>>> origin/develop:doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
This is a merge conflict that needs to be resolved.

2024-09-13 14:49 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +>>>>>>> origin/develop:doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
Another merge conflict that needs to be resolved.

2024-09-13 14:50 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +
```suggestion
```
This variable is listed above.

2024-09-13 14:50 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +
```suggestion
```
This variable is listed above.

2024-09-13 14:51 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +
```suggestion
```
Variable already included

2024-09-13 14:51 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +>>>>>>> origin/develop:doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
Merge conflict that needs to be resolved.

2024-09-13 14:51 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +>>>>>>> origin/develop:doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
Merge conflict that needs to be resolved.

2024-09-13 14:52 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +>>>>>>> origin/develop:doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
Merge conflict that needs to be resolved.

2024-09-13 14:55 UTC, gspetro-NOAA commented
@jdkublnick I think the only changes required are from [PR #1098](https://github.com/ufs-community/ufs-srweather-app/commit/c377164582ee071ce8b3921e10b2d0f100141887#diff-a4384c6e3a35bddb4828a36142825b542f035fac5ea6df0e7b72e1c2a56bb4e5). Pretty much everything else should remain as-is.

2024-09-13 15:05 UTC, gspetro-NOAA commented
@MichaelLueken I think "Path to system directory..." is more accurate than "System directory where...". As far as I can tell, users would need to add the full path to the directory, not just the name of the directory, and the "Path to..." makes that clearer imo. Looking at, e.g., the [Hera machine file](https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/machine/hera.yaml), `FIXaqm` and similar variables are defined using a full path. I presume a user would need to change the path, not just the directory name, if their data is located somewhere else on their system. In that respect, it could be better to update the `config_defaults.yaml` file comments, but I have hesitated to overwrite what developers have put in. That said, the RST files are more clearly within our purview, and I have improved definitions where possible.

2024-09-13 15:10 UTC, MichaelLueken commented
Thanks for the explanation, @gspetro-NOAA!  I'm fine with keeping `config_defaults.yaml` as it currently is and providing more detailed information in the User Guide documentation.

2024-09-13 16:23 UTC, MichaelLueken reviewed
@jdkublnick 

Thanks for merging the latest develop into text/us-336!  The `OMP_NUM_THREADS_RUN_FCST` default value should be 2, rather than 1.

2024-09-13 16:23 UTC, MichaelLueken commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
>  ``OMP_NUM_THREADS_RUN_FCST``: (Default: 1)
The defaults for OMP_NUM_THREADS_RUN_FCST should be 2.

```suggestion
``OMP_NUM_THREADS_RUN_FCST``: (Default: 2)
```

2024-09-13 16:33 UTC, MichaelLueken approved these changes
Thanks again, @jdkublnick!

The differences between the `config_defaults.yaml` and `ConfigWorkflow.rst` files appear to be addressed now.

2024-09-13 16:34 UTC, gspetro-NOAA commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +  Name of a template file that contains information about the various UFS components and their run sequence (ufs-weather-model: ufs.configure). Its default value is the name of the file that the ufs
```suggestion
   Name of a template file that contains information about the various :term:`UFS` components and their run sequence. In general, users should not set this variable in their configuration file (see :ref:`note <tmpl-fn-warning>`).
```
@jdkublnick I'd like to revert this definition to what is in `develop` already, tho you can keep the addition of the word "template."

2024-09-16 19:52 UTC, gspetro-NOAA approved these changes
Requested changes were made. Looks good to me.

2024-09-16 20:03 UTC, MichaelLueken commented
Moving forward with merging this work now.

2024-09-16 20:04 UTC, merged