Port SRW to Gaea C6
ufs-community/ufs-srweather-app pull request #1163
Opened 2024-12-04 17:00 UTC by RatkoVasic-NOAA

## DESCRIPTION OF CHANGES: 
Enable SRW for new machine Gaea-C6

**NOTE**: needs to update SRW to new UFS-WM version (after [PR2448](https://github.com/ufs-community/ufs-weather-model/pull/2448))

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update (updated in this PR)

## TESTS CONDUCTED: 

- [ ] derecho.intel
- [ ] gaea-c5.intel
- [x] gaea-c6.intel - comprehensive
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [ ] jet.intel
- [ ] orion.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
- ufs-community/ufs-weather-model/pull/[2448](https://github.com/ufs-community/ufs-weather-model/pull/2448) Issue: [#2407](https://github.com/ufs-community/ufs-weather-model/issues/2407)

## DOCUMENTATION:
rst files updated.

## ISSUE: 
Closes issue #1120 

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 
A Code Manager needs to add the following labels to this PR: 
- [x] Work In Progress
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [x] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

2024-12-04 17:04 UTC, RatkoVasic-NOAA commented
Passed comprehensive tests:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
2020_CAD_20241204002937                                            COMPLETE              41.87
2020_CAPE_20241204003011                                           COMPLETE              43.16
2019_hurricane_barry_20241204003011                                COMPLETE              41.60
2019_halloween_storm_20241204003012                                COMPLETE              53.42
2019_hurricane_lorenzo_20241204003012                              COMPLETE              48.37
2019_memorial_day_heat_wave_20241204003013                         COMPLETE              50.84
2020_denver_radiation_inversion_20241204003014                     COMPLETE              41.79
2020_easter_storm_20241204003014                                   COMPLETE              42.76
2020_jan_cold_blast_20241204003015                                 COMPLETE              44.63
community_20241204003015                                           COMPLETE              24.79
custom_ESGgrid_20241204003016                                      COMPLETE              30.05
custom_ESGgrid_Central_Asia_3km_20241204003016                     COMPLETE              33.77
custom_ESGgrid_IndianOcean_6km_20241204003017                      COMPLETE              23.92
custom_ESGgrid_NewZealand_3km_20241204003017                       COMPLETE              88.16
custom_ESGgrid_Peru_12km_20241204003056                            COMPLETE              27.01
custom_ESGgrid_SF_1p1km_20241204003057                             COMPLETE             262.59
custom_GFDLgrid__GFDLgrid_USE_NUM_CELLS_IN_FILENAMES_eq_FALSE_202  COMPLETE              10.53
custom_GFDLgrid_20241204003132                                     COMPLETE               9.44
deactivate_tasks_20241204003132                                    COMPLETE               1.13
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE             974.46
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_20241204003133              COMPLETE              13.86
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_202  COMPLETE               9.39
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_  COMPLETE             377.41
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20241  COMPLETE             138.34
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20241204003210  COMPLETE             267.88
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241204003  COMPLETE              45.10
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              50.35
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024120400  COMPLETE              55.12
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              74.02
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               6.27
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              22.12
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              18.96
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024120400  COMPLETE              18.61
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241204003  COMPLETE              54.79
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              23.36
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_RAP_20241204003217  COMPLETE              13.82
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2_20241  COMPLETE               9.88
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024120400321  COMPLETE              42.45
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta_202412040  COMPLETE              19.51
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_202412  COMPLETE             319.71
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             485.13
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_20241204  COMPLETE             497.48
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20241204003  COMPLETE             511.55
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_2024  COMPLETE             510.44
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_  COMPLETE              41.38
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR_20241204  COMPLETE              34.99
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              39.68
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_  COMPLETE              11.70
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024120  COMPLETE              32.31
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              11.03
grid_RRFS_CONUScompact_25km_ics_RRFS_lbcs_RRFS_suite_RRFS_v1beta_  COMPLETE              14.20
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_2  COMPLETE             394.59
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR_202412040  COMPLETE             417.01
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             428.75
grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241204003229  COMPLETE              93.25
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0_202412  COMPLETE              31.25
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024120400323  COMPLETE              23.93
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241204003  COMPLETE              18.41
grid_SUBCONUS_Ind_3km_ics_NAM_lbcs_NAM_suite_GFS_v16_202412040032  COMPLETE              24.20
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              11.92
MET_ensemble_verification_only_vx_20241204003234                   COMPLETE               0.88
MET_ensemble_verification_winter_wx_20241204003236                 COMPLETE             138.80
MET_verification_only_vx_20241204003237                            COMPLETE               0.26
pregen_grid_orog_sfc_climo_20241204003239                          COMPLETE               9.91
specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS_20241204003241               COMPLETE               8.82
specify_template_filenames_20241204003242                          COMPLETE               9.97
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            7277.08

Detailed summary written to /gpfs/f6/bil-fire8/world-shared/Ratko.Vasic/SRW/expt_dirs/WE2E_summary_20241204031723.txt

```
For runs used UFS-WM branch: https://github.com/BrianCurtis-NOAA/ufs-weather-model.git -b gaeac6 [PR#2448](https://github.com/ufs-community/ufs-weather-model/pull/2448)

2024-12-19 19:49 UTC, MichaelLueken commented
@RatkoVasic-NOAA I have discussed the Jenkins labels for Gaea-C5 and Gaea-C6 with Kris Booker.  The newly added `gaea-c6` label will work in Jenkins, but there are no plans for changing the current `gaea` label to `gaea-c5`.  We will need to change the `gaea-c5` entries back to `gaea`, otherwise the automated tests will fail.

I'm working in a copy of your branch to remove `-c5` from `gaea-c5` throughout your `gaea-c6` branch.  I'll let you know and open a PR into your branch once the automated build and run scripts work on Gaea using `gaea` rather than `gaea-c5`.

2024-12-19 20:19 UTC, RatkoVasic-NOAA commented
@MichaelLueken that's OK. I'm currently running tests on: Hera, Hercules, Jet, Orion, Gaea-C5, Gaea-C6, and Derecho. Some are already done. I'll retest gaea-c5 after your changes.

2024-12-19 21:55 UTC, MichaelLueken commented
@RatkoVasic-NOAA The majority of the modifications have been made and the both the automated build script (`srw_build.sh`) and the wrapper test script (`wrapper_srw_ftest.sh`) have been successfully tested on Gaea-C5, following the changes from `gaea-c5` back to `gaea`.  The final `srw_test.sh` script is now running.  I should be able to open a PR into your `gaea-c6` branch in the morning.

2024-12-20 01:27 UTC, RatkoVasic-NOAA commented
Hera:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              13.62
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               9.53
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              26.56
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              44.96
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219180  COMPLETE              25.86
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121918043  COMPLETE              48.59
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             169.12
```
Jet:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              12.26
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               9.97
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              28.55
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              49.54
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219210  COMPLETE              31.96
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121921091  COMPLETE              48.82
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             181.10

```
Gaea-c6:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              10.32
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               8.07
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              19.36
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              30.18
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219150  COMPLETE              15.71
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121915080  COMPLETE              39.11
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             122.75

```
Orion:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              17.78
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE              12.36
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              41.80
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              48.84
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219145  COMPLETE              32.64
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121914553  COMPLETE              79.76
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             233.18

```
Hercules:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              10.50
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               8.09
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              22.77
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              41.00
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219120  COMPLETE              27.51
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121912043  COMPLETE              39.71
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             149.58

```
Derecho:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              18.77
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE              15.59
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              36.19
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              56.55
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241219135  COMPLETE              27.86
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121913560  COMPLETE              64.30
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             219.26

```

2024-12-20 14:00 UTC, MichaelLueken commented
@RatkoVasic-NOAA PR [#15](https://github.com/RatkoVasic-NOAA/ufs-srweather-app/pull/15) was created in your fork.  Once merged, this PR will be ready for review.

2025-01-09 21:02 UTC, MichaelLueken requested changes
@RatkoVasic-NOAA -

I'm building the SRW App on Gaea-C6 using the Jenkins scripts.  Once built, I will run the fundamental WE2E tests using the Jenkins scripts as well.  I'll run the Jenkins task test script after the fundamental tests successfully finish.  I should be able to approve the changes once those tests are complete.

I noted one minor issue with the `doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst` file.  There is still mention of `GAEA-C5` and `GAEA-C6`, rather than `GAEA` and `GAEA-C6`.  Please remove the `-C5` from `GAEA-C5` on line 33 of the rst file.

2025-01-09 21:02 UTC, MichaelLueken commented on doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst
> +   The machine (a.k.a. platform or system) on which the workflow will run. Currently supported platforms are listed on the :srw-wiki:`SRW App Wiki page <Supported-Platforms-and-Compilers>`. When runn
Please change `GAEA-C5` to `GAEA`.

2025-01-09 21:46 UTC, MichaelLueken commented
The Jenkins `srw_build.sh` script successfully built the SRW on Gaea-C6.  The srw_test.sh script was modified to run the fundamental tests on Gaea-C6 and all tests successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              10.22
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20250  COMPLETE               9.28
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              26.49
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2025010  COMPLETE             164.98
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20250109161  COMPLETE              20.41
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2025010916164  COMPLETE              48.78
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             280.16
```
Submitting the `wrapper_srw_ftest.sh` script now.

2025-01-10 13:43 UTC, MichaelLueken commented
The `Functional Tasks Test` has successfully passed on Gaea-C6 using the `wrapper_srw_ftest.sh` script:
```
# Try gaea-c6 with the first few simple SRW tasks ...
run_make_grid: COMPLETE
run_get_ics: COMPLETE
run_get_lbcs: COMPLETE
run_make_orog: COMPLETE
run_make_sfc_climo: COMPLETE
run_make_ics: COMPLETE
run_make_lbcs: COMPLETE
run_fcst: COMPLETE
run_post: COMPLETE
```

2025-01-10 13:45 UTC, MichaelLueken approved these changes
Thanks for making the change, @RatkoVasic-NOAA!  Everything looks great and the Jenkins scripts are working correctly on Gaea-C6.  I will now approve this PR.

2025-01-10 18:11 UTC, MichaelLueken commented
I was also able to successfully run the UFS-Fire WE2E tests on Gaea-C6:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
UFS_FIRE_multifire_one-way-coupled_20250110125635                  COMPLETE              17.47
UFS_FIRE_one-way-coupled_20250110125635                            COMPLETE              17.40
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              34.87
```

2025-01-10 18:56 UTC, rickgrubin-tomorrow approved these changes
LGTM

2025-01-10 19:24 UTC, EdwardSnyder-NOAA commented
Ran fundamental test on Gaea c6 and it passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              10.40
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20250  COMPLETE               7.78
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              20.05
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2025011  COMPLETE              30.20
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20250110132  COMPLETE              17.97
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2025011013251  COMPLETE              45.22
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             131.62

```
Experienced strange behaviors were the devbuild script didn't build the `srw_app` conda env and the `make_ics` task failed for an experiment. Both issues were resolved by re-running their corresponding scripts (devbuild with the conda-only option for the conda env and rocotorewind for the `make_ics` task.

2025-01-10 19:25 UTC, EdwardSnyder-NOAA approved these changes

2025-01-10 19:32 UTC, MichaelLueken commented
Jenkins is not yet running on Gaea-C6, so I will manually run the coverage tests on that machine.  Additionally, Hera epic space has exceeded disk quota, so will manually run in stmp space.

2025-01-10 21:30 UTC, MichaelLueken commented
The coverage tests have successfully passed on Gaea-C6:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20250110151055                                           COMPLETE              23.24
custom_ESGgrid_NewZealand_3km_20250110151059                       COMPLETE              78.88
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              41.56
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20250110151  COMPLETE              59.20
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2025011015  COMPLETE              57.33
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             480.58
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2025011  COMPLETE              37.01
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             432.59
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              17.09
2020_CAPE_20250110151134                                           COMPLETE              42.11
2020_easter_storm_20250110151138                                   COMPLETE              40.97
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1310.56
```

2025-01-10 21:33 UTC, MichaelLueken commented
The Hera Intel coverage WE2E tests have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
2019_memorial_day_heat_wave_20250110201104                         COMPLETE              64.11
custom_ESGgrid_Peru_12km_20250110201105                            COMPLETE              42.05
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200_2025011  COMPLETE              10.93
get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2  COMPLETE            1759.62
get_from_HPSS_ics_HRRR_lbcs_RAP_20250110201107                     COMPLETE              21.46
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              27.80
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_RAP_20250110201109  COMPLETE              15.75
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2_20250  COMPLETE              11.24
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_202501  COMPLETE             550.31
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_20250110  COMPLETE             726.12
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR_202501102  COMPLETE             733.17
pregen_grid_orog_sfc_climo_20250110201114                          COMPLETE              12.04
vx-det_long-fcst_custom-vx-config_aiml-graphcast_20250110201115    COMPLETE               0.75
vx-det_multicyc_long-fcst-overlap_nssl-mpas_20250110201117         COMPLETE              12.58
vx-det_multicyc_long-fcst-no-overlap_nssl-mpas_20250110201119      COMPLETE              13.89
vx-det_multicyc_first-obs-00z_ncep-hrrr_20250110201121             COMPLETE               0.95
vx-det_multicyc_no-00z-obs_nssl-mpas_20250110201122                COMPLETE               0.92
vx-det_multicyc_no-fcst-overlap_ncep-hrrr_20250110201124           COMPLETE               2.11
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            4005.80
```

2025-01-11 13:36 UTC, chan-hoo commented
@RatkoVasic-NOAA @MichaelLueken , I am trying to run the sample configuration on Gaea-c6, but the `make_grid` task does not started even though it looks submitted as follows:
```
201906151800               make_grid                   207521833              QUEUED                   -         0           0.0
```
The `get_extrn_ics/lbcs` tasks are working well though:
```
-rw-r--r-- 1 Chan-hoo.Jeon ncep  466 Jan 11 07:49 FV3LAM_wflow.log
-rw-r--r-- 1 Chan-hoo.Jeon ncep 6632 Jan 11 07:52 get_extrn_ics_2019061518.log
-rw-r--r-- 1 Chan-hoo.Jeon ncep 7502 Jan 11 07:52 get_extrn_lbcs_2019061518.log
```
Do you have any idea what is wrong? I am using `bil-fire8` for this run.

2025-01-13 13:38 UTC, chan-hoo commented
@RatkoVasic-NOAA @MichaelLueken , I found out I should have run it in `/gpfs/f6` directory. I ran it in `/ncrc/` dir. 
BTW, I found something strange in the `machine/gaea-c6.yaml`. Based on the Gaea user's guide, I think `QOS` and `Partitions` can be set as follows:
```
  QUEUE_DEFAULT: normal
  QUEUE_FCST: normal
  QUEUE_HPSS: hpss
  PARTITION_DEFAULT: batch
  PARTITION_FCST: batch
  PARTITION_HPSS: eslogin_c6
  SCHED_NATIVE_CMD: -M c6 --export=NONE
  SCHED_NATIVE_CMD_HPSS: -M es --export=NONE
```
What do you think about this?

2025-01-13 14:18 UTC, MichaelLueken commented
> @RatkoVasic-NOAA @MichaelLueken , I found out I should have run it in `/gpfs/f6` directory. I ran it in `/ncrc/` dir. BTW, I found something strange in the `machine/gaea-c6.yaml`. Based on the Gaea user's guide, I think `QOS` and `Partitions` can be set as follows:
> 
> ```
>   QUEUE_DEFAULT: normal
>   QUEUE_FCST: normal
>   QUEUE_HPSS: hpss
>   PARTITION_DEFAULT: batch
>   PARTITION_FCST: batch
>   PARTITION_HPSS: eslogin_c6
>   SCHED_NATIVE_CMD: -M c6 --export=NONE
>   SCHED_NATIVE_CMD_HPSS: -M es --export=NONE
> ```
> 
> What do you think about this?

@chan-hoo, the settings in the `machine/gaea-c6.yaml` file are mirroring what has been done for Gaea-C5, just using `f6` instead of `f5` and `bil-fire8` instead of `epic`.  Since HPSS isn't available on Gaea-C6 (at least not yet):
```
Michael.Lueken@gaea61:/gpfs/f6/bil-fire8/scratch/Michael.Lueken> module spider hpss
Lmod has detected the following error:  Unable to find: "hpss".
```
using the settings currently in `machine/gaea-c6.yaml` is fine for running the SRW (both standard WE2E tests and UFS-Fire WE2E tests) on the machine.  Leaving it as is is fine (at least until HPSS is available, if it ever is).

2025-01-13 14:27 UTC, MichaelLueken commented
The Jenkins tests completed.  The tests on Derecho, Hercules, Jet, and Orion successfully passed.

The Jenkins runner lost communication with Gaea during the `Test` phase, leading to the test showing as aborted in the Jenkins API.  The tests did successfully pass (from `/gpfs/f5/epic/scratch/role.epic/jenkins/workspace/SRW_App_Jenkinsfile_test_PR-1163/gaea/expt_dirs`):
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20250110165501                                           COMPLETE              96.69
custom_ESGgrid_NewZealand_3km_20250110165503                       COMPLETE             204.93
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE             151.53
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20250110165  COMPLETE             163.11
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2025011016  COMPLETE             134.68
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE            1074.38
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2025011  COMPLETE             163.16
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             900.41
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              57.50
2020_CAPE_20250110165537                                           COMPLETE             198.17
2020_easter_storm_20250110165538                                   COMPLETE             162.15
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            3306.71
```
The Hera GNU WE2E coverage tests have also successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Central_Asia_3km_20250110215718                     COMPLETE             341.13
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200_202501  COMPLETE              16.77
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_20250110215720              COMPLETE              24.61
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2025011021  COMPLETE             477.69
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              35.30
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20250110215  COMPLETE              35.97
long_fcst_20250110215723                                           COMPLETE             400.20
MET_verification_only_vx_20250110215724                            COMPLETE               0.40
MET_ensemble_verification_only_vx_time_lag_20250110215726          COMPLETE              13.17
2019_halloween_storm_20250110215728                                COMPLETE             705.02
2020_jan_cold_blast_20250110215729                                 COMPLETE             761.41
vx-det_long-fcst_custom-vx-config_aiml-fourcastnet_20250110215729  COMPLETE               0.88
vx-det_long-fcst_custom-vx-config_aiml-panguweather_2025011021573  COMPLETE               0.86
vx-det_long-fcst_custom-vx-config_gfs_20250110215733               COMPLETE               0.90
vx-det_long-fcst_winter-wx_SRW-staged_20250110215735               COMPLETE               1.58
vx-det_multicyc_fcst-overlap_ncep-hrrr_20250110215736              COMPLETE               7.63
vx-det_multicyc_last-obs-00z_ncep-hrrr_20250110215738              COMPLETE               1.45
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            2824.97
```
With this, all WE2E coverage tests have successfully passed.  Once discussions on the `machine/gaea-c6.yaml` file with @chan-hoo and @RatkoVasic-NOAA are complete, will move forward with merging this work.

2025-01-13 14:33 UTC, chan-hoo commented
@MichaelLueken , `partitions` are supposed to be set with:
```
  PARTITION_DEFAULT:
  PARTITION_FCST:
  PARTITION_HPSS:
```
However, they are duplicated in the `SCHED_NATIVE_` command lines:
```
SCHED_NATIVE_CMD: --clusters=c6 --partition=batch --export=NONE
```

2025-01-13 14:52 UTC, MichaelLueken commented
@chan-hoo, there is nothing currently in the SRW App's standards that require the use of `PARTITION_DEFAULT`, `PARTITION_FCST`, AND `PARTITION_HPSS` in the machine yaml file.  However, I do agree with you that this is what is set in the rest of the non-gaea machine yaml files.  As you also noted, `PARTITION_HPSS` is being set, but is also duplicated in `SCHED_NATIVE_CMD_HPSS` in the current `machine/gaea-c6.yaml` file.

Please feel free to request a change to have @RatkoVasic-NOAA update the `machine/gaea-c6.yaml`, using `PARTITION_DEFAULT` and `PARTITION_FCST`, and remove the `--partition` from the `SCHED_NATIVE_CMD_*` entries.  As noted above, I'll hold off on merging this work until you and @RatkoVasic-NOAA are happy with the changes.

2025-01-13 15:54 UTC, MichaelLueken commented
Discussing this during the daily scrum this morning, @chan-hoo and I have agreed to move forward with merging this work to develop at this time.  I have opened issue #1176, so that I can make changes to both Gaea C5 and Gaea C6 machine files so that they follow the same standard as the rest of the machine files.

2025-01-13 15:56 UTC, merged