[develop] Update SRW container docs to reflect latest container
ufs-community/ufs-srweather-app pull request #1170
Opened 2024-12-24 21:49 UTC by EdwardSnyder-NOAA

## DESCRIPTION OF CHANGES: 

The SRW App container was updated to work with the head of develop. This new container was built from this [Dockerfile](https://github.com/NOAA-EPIC/ufs-containers/blob/feature/unified-1.6.0/Docker/srw/Dockerfile.ubuntu22.04-intel21.10-ue160-fms202401-srw) and can be found in [dockerhub](https://hub.docker.com/layers/noaaepic/ubuntu22.04-intel21.10-srw/ue160-fms202401-dev/images/sha256-5ba117bc5c1898e9b9c3abfc7228a308d70bf83ff04d890f63f2d5cf08032924). The docker container was then converted to a singularity container and staged on each T1 platforms. The container passes on most T1 platforms with the exceptions being tracked in our JIRA system.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [ ] jet.intel
- [ ] orion.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:

## DOCUMENTATION:

Updates container documentation.

## ISSUE: 

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

## CONTRIBUTORS (optional):

2025-01-08 16:17 UTC, MichaelLueken commented
@EdwardSnyder-NOAA -

The documentation updates that you have made for the new container look good.  Before I give my approval, please merge the latest HEAD of develop into your `srw-container-151` branch branch.  I want to make sure that the `doc_tests` GitHub Action successfully passes after merging the documentation fix from yesterday, then I can approve these changes.  Thanks!

2025-01-08 16:55 UTC, MichaelLueken requested changes
@EdwardSnyder-NOAA -

The `doc_tests` show that there is a warning due to `SetUpPythonEnvC` still being referenced on line 369.  Please change this to the new `SetUpCont` reference.  Thanks!

2025-01-08 16:55 UTC, MichaelLueken commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
On line 369, there is still a reference to `SetUpPythonEnvC`.  It appears as though this has been changed to `SetUpCont` in this PR.  Please replace `SetUpPythonEnvC` with `SetUpCont` on line 369.

2025-01-08 17:53 UTC, EdwardSnyder-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
should be fixed now

2025-01-08 18:01 UTC, MichaelLueken commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
It looks like `SetUpPythonEnvC` is still present on line 369.  The modification you made was replacing `SetUpConfigFileC` with `SetUpCont`, while it should have been `SetUpPythonEnvC` to `SetUpCont`.

2025-01-08 18:13 UTC, MichaelLueken commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
Thanks @EdwardSnyder-NOAA!  The `doc_tests` GitHub Action has successfully passed.  I will approve this PR now.

2025-01-08 18:14 UTC, MichaelLueken approved these changes
Thanks for modifying line 369, @EdwardSnyder-NOAA!  I will now approve these changes.

2025-01-08 18:15 UTC, EdwardSnyder-NOAA commented
Thanks for catching this!

2025-01-08 18:15 UTC, EdwardSnyder-NOAA commented
> Thanks for modifying line 369, @EdwardSnyder-NOAA! I will now approve these changes.

Thank you for catching this!

2025-01-28 17:55 UTC, gspetro-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
> +   * ``-m`` indicates the :term:`MPI` on the user's local machine (e.g., ``impi/2022.1.2``)
@EdwardSnyder-NOAA In the Land DA PR, you listed a few more examples. Do those examples belong here as well?

2025-01-28 21:03 UTC, EdwardSnyder-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
> +   * ``-m`` indicates the :term:`MPI` on the user's local machine (e.g., ``impi/2022.1.2``)
yeah, we could add those examples to here as well.

2025-01-28 23:40 UTC, EdwardSnyder-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
> +   * ``-m`` indicates the :term:`MPI` on the user's local machine (e.g., ``impi/2022.1.2``)
added them

2025-01-29 21:34 UTC, gspetro-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
> +   dev      gpfs         lfs3  libx32  proc    scratch1  third-party-programs.txt  work
```suggestion
autofs	 dev	      gpfs	  lfs2	 lib64	 ncrc  sbin	    srv			      u
bin	 discover     home	  lfs3	 libx32  opt   scratch	    sw			      usr
boot	 environment  host_lib64  lfs4	 lustre  proc  scratch1     sys			      usw
contrib  etc	      lfs	  lib	 media	 root  scratch2     third-party-programs.txt  var
data	 glade	      lfs1	  lib32  mnt	 run   singularity  tmp			      work
```

2025-02-04 16:22 UTC, gspetro-NOAA commented on doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst
> +data	 glade	      lfs1	  lib32  mnt	 run   singularity  tmp			      work
```suggestion
   autofs	 dev	      gpfs	  lfs2	 lib64	 ncrc  sbin	    srv			      u
   bin	 discover     home	  lfs3	 libx32  opt   scratch	    sw			      usr
   boot	 environment  host_lib64  lfs4	 lustre  proc  scratch1     sys			      usw
   contrib  etc	      lfs	  lib	 media	 root  scratch2     third-party-programs.txt  var
   data	 glade	      lfs1	  lib32  mnt	 run   singularity  tmp			      work
```

2025-02-05 22:51 UTC, gspetro-NOAA approved these changes
Documentation updates work on Orion/Hercules. 
Although it has issues on Gaea, there is already a note to that effect in the documentation. 
Would be good to have the container working on all systems for the v3.0.0 release, but for `develop`, this is fine; it keeps all the current functionality.

2025-02-06 13:48 UTC, MichaelLueken commented
@EdwardSnyder-NOAA -

There is currently a conflict in `doc/UsersGuide/BuildingRunningTesting/ContainerQuickstart.rst`.  Please merge the latest develop into your `srw-container-151` branch and address the conflict, then I will be able to merge this work.  Thanks!

2025-02-06 14:10 UTC, merged