[develop]: Updates for building and running SRW on MacOS platform
ufs-community/ufs-srweather-app pull request #1171
Opened 2024-12-27 18:13 UTC by natalie-perlin

## DESCRIPTION OF CHANGES: 
Updated scripts and modulefiles to ensure SRW could be built and run on MacOS. 
Building could be done using devbuild.sh script.
Running MacOS is done using standalone scripts located in ./ush/wrappers/*.

Building the UFS weather model code includes use of CXX linker instead of Fortran linker, the change of a CMakeLists.txt file for the WM is done in devbuild.sh.

Software packages mostly correspond spack-stack-1.8.0. Directions for building the sofware stack and running the SRW are included below in two separate links to documents (working copies).

Running SRW on MacOS:
https://docs.google.com/document/d/1ADfLi4Yaa25IXz7ZhGxoRlDcmvATIlRD0KI9Se-ZJ3c/edit?usp=sharing

Building spack-stack on MacOS for UFS-WM and SRW:
https://docs.google.com/document/d/1Z0L7eujZGtyeZRzcgguyZPsZpkwb2Om7UhFqQPVtxnE/edit?usp=sharing

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
Tests are conducted on three different MacOS platforms
- x86_64, Sonoma OS 14.7.2, XCode 15.4, clang@15.0.0, gcc@13.3.0
- M1 , Sonoma OS 14.7.2, XCode 15.4, clang@15.0.0, gcc@13.3.0
- (NOAA AWS MacOS instance) M2, Ventura OS 13.6.9, xcode-select command-line tools only; clang@15.0.0, gcc@13.3.0

-->

- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [ ] jet.intel
- [ ] orion.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
A PR to the UFS-WM has been submitted: https://github.com/ufs-community/ufs-weather-model/pull/2551
Current version of devbuild.sh assumes no changes to weather-model CMakeFiles.txt has been made.

## DOCUMENTATION:
Documentation may need to be updated to reflect a new option to use devbuild.sh script for the build on MacOS platform.

## ISSUE: 
Addresses the issue mentioned in https://github.com/ufs-community/ufs-srweather-app/issues/1168
Documentation lists only CMake approach to be used on MacOS. It creates errors on MacOS, as well as requires additional steps (not documented) required for running the SRW. Adapted devbuild.sh script allows SRW to be built on MacOS.

Addressed the issue of running UFS WM on MacOS mentioned in https://github.com/ufs-community/ufs-weather-model/discussions/2371

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [x] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

## CONTRIBUTORS (optional):

2024-12-28 01:27 UTC, rickgrubin-noaa approved these changes
LGTM

2024-12-30 13:05 UTC, gspetro-NOAA requested changes
I know this is in draft form, so perhaps you were already planning to do this, but the Google docs version of the documentation needs to be added to the authoritative SRW documentation (particularly the RunSRW chapter) where it differs from what's already there. Normally, I'd leave the change request till the PR is fully open, but since it already has an approval, I wanted to make sure that doesn't get missed. :)

2024-12-30 17:03 UTC, RatkoVasic-NOAA approved these changes
Looks good to me. Approving.

2025-01-14 21:49 UTC, ulmononian commented on modulefiles/srw_common.lua
> +load("parallelio/2.6.2")
@natalie-perlin @RatkoVasic-NOAA are these library version changes specific for the macos stack built to enable the srw community test? are these lib updates consistent with the stack used by all other machines in srw_common?

2025-01-14 21:55 UTC, RatkoVasic-NOAA commented on modulefiles/srw_common.lua
> +load("parallelio/2.6.2")
This wouldn't work on develop branch (other machines) since SRW/WM are still using spack-stack@1.6.0.

2025-01-14 22:23 UTC, ulmononian commented on modulefiles/srw_common.lua
> +load("parallelio/2.6.2")
i think srw common should not be changed then and explicit lib loads need to go into the mac os modulefile

2025-01-23 16:49 UTC, natalie-perlin commented on modulefiles/srw_common.lua
> +load("parallelio/2.6.2")
The versions of packages built in spack-stack could be tailored to whatever is needed for the repository. 
This work on MacOS started when there were plans to continue with spack-stack-1.8.0 for the UFS-WM and updated package versions. Going back to use lower versions of the packages is always an option.

2026-08-06 18:37 UTC, MichaelLueken commented
@natalie-perlin - Given that the SRW App is in the deprecation process and only Gaea C6 will be supported for ARL related AQMv8 work, is it okay to close out this PR?

2026-08-06 18:42 UTC, MichaelLueken commented
Given ongoing deprecation plans, and only Gaea C6 support will be provided moving forward, this PR will not be closed.

2026-08-06 18:42 UTC, closed without merging