Update fork with all prior local edits
ufs-community/ufs-srweather-app pull request #209
Opened 2022-02-07 17:59 UTC by kb1kgp

- Rearranged index/TOC to follow installation chronological order
- Created HPC Stack Install doc
- Making Introduction section more newbie-friendly and concise
- Created Components doc to relocate detailed info from the Introduction
- Updated Quickstart to include tips beyond Level 1 systems & to reflect HPC Stack install
- Added cross-references to other chapters from Quickstart
- Added terms to Glossary

2022-02-07 19:00 UTC, JeffBeck-NOAA requested changes
Gillian, thanks for opening this draft PR.  Could you use the official PR template that you see in other PR conversation tabs?  That helps to identify changes, tests run, documentation changes, etc.  Also, please remove the ".DS_Store" binary files from the PR.  Thanks!

2022-02-07 19:00 UTC, JeffBeck-NOAA commented on docs/UsersGuide/source/ConfigNewPlatform.rst
>     +--------------------+----------------------------+------------+-----------+
This needs to stay UPP.  It was recently changed and updated in the umbrella repo.

2022-02-07 19:00 UTC, JeffBeck-NOAA commented on docs/UsersGuide/source/CodeReposAndDirs.rst
>     | Repository for                  | https://github.com/ufs-community/ufs-weather-model      |
This file shouldn't change, as it was updated recently to account for the new GitHub organization used for regional_workflow and the name change for UPP.

2022-02-07 19:00 UTC, JeffBeck-NOAA commented on docs/UsersGuide/source/ConfigParameters.inc
>     The full path to the custom post flat file, including filename, to be used for post-processing. This is only used if ``CUSTOM_POST_CONFIG_FILE`` is set to "TRUE".
This file shouldn't change (needs to stay as "UPP").

2022-02-07 19:18 UTC, kb1kgp commented
Will do! Didn't realize you could see the draft... It's definitely still a
draft as the Introduction is only half done, it's got comments all over,
and we haven't finished running the SRW on all systems!

Best,
Gillian

On Mon, Feb 7, 2022 at 2:01 PM JeffBeck-NOAA ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Gillian, thanks for opening this draft PR. Could you use the official PR
> template that you see in other PR conversation tabs? That helps to identify
> changes, tests run, documentation changes, etc. Also, please remove the
> ".DS_Store" binary files from the PR. Thanks!
> ------------------------------
>
> In docs/UsersGuide/source/ConfigNewPlatform.rst
> <https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800963867>
> :
>
> > @@ -275,7 +275,7 @@ The ``README.md`` file will contain instructions on the order that each script s
>
>     +--------------------+----------------------------+------------+-----------+
>
>     | ufs-weather-model  | ./run_fcst.sh              | 6          | 1h 40 m   |
>
>     +--------------------+----------------------------+------------+-----------+
>
> -   | UPP                | ./run_post.sh              | 1          | 7 m       |
>
> +   | EMC_post           | ./run_post.sh              | 1          | 7 m       |
>
>     +--------------------+----------------------------+------------+-----------+
>
>
> This needs to stay UPP.
> ------------------------------
>
> In docs/UsersGuide/source/CodeReposAndDirs.rst
> <https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800964100>
> :
>
> > @@ -30,14 +30,14 @@ repositories associated with this umbrella repo (see :numref:`Table %s <top_leve
>
>     | Repository for                  | https://github.com/ufs-community/ufs-weather-model      |
>
>
> This file shouldn't change, as it was updated recently to account for the
> new GitHub organization used for regional_workflow and the name change for
> UPP.
> ------------------------------
>
> In docs/UsersGuide/source/ConfigParameters.inc
> <https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800965036>
> :
>
> > @@ -310,7 +310,7 @@ Maximum number of attempts.
>
>  Customized Post Configuration Parameters
>
>  ========================================
>
>  ``USE_CUSTOM_POST_CONFIG_FILE``: (Default: “FALSE”)
>
> -   Flag that determines whether a user-provided custom configuration file should be used for post-processing the model data. If this is set to "TRUE", then the workflow will use the custom post-processing (UPP) configuration file specified in ``CUSTOM_POST_CONFIG_FP``. Otherwise, a default configuration file provided in the UPP repository will be used.
>
> +   Flag that determines whether a user-provided custom configuration file should be used for post-processing the model data. If this is set to "TRUE", then the workflow will use the custom post-processing (UPP) configuration file specified in ``CUSTOM_POST_CONFIG_FP``. Otherwise, a default configuration file provided in the EMC_post repository will be used.
>
>
>
>  ``CUSTOM_POST_CONFIG_FP``: (Default: “”)
>
>     The full path to the custom post flat file, including filename, to be used for post-processing. This is only used if ``CUSTOM_POST_CONFIG_FILE`` is set to "TRUE".
>
>
> This file shouldn't change (needs to stay as "UPP").
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ufs-srweather-app/pull/209#pullrequestreview-875116323>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDGAEYWHDZ7Y4XCTKPKIK3U2AJFHANCNFSM5NYFG4TA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-07 19:21 UTC, ligiabernardet reviewed
I know this is just a draft, but I thought I'd leave a comment. It is great to have HPC Stack documentation. I recommend coming up with a mechanism to make it usable for other Apps and also for standalone installation. For example: create some a standalone rst file and include it in the SRW App User's Guide.

2022-02-07 19:59 UTC, JeffBeck-NOAA commented
> Will do! Didn't realize you could see the draft... It's definitely still a draft as the Introduction is only half done, it's got comments all over, and we haven't finished running the SRW on all systems! Best, Gillian
> […](#)
> On Mon, Feb 7, 2022 at 2:01 PM JeffBeck-NOAA ***@***.***> wrote: ***@***.**** requested changes on this pull request. Gillian, thanks for opening this draft PR. Could you use the official PR template that you see in other PR conversation tabs? That helps to identify changes, tests run, documentation changes, etc. Also, please remove the ".DS_Store" binary files from the PR. Thanks! ------------------------------ In docs/UsersGuide/source/ConfigNewPlatform.rst <[#209 (comment)](https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800963867)> : > @@ -275,7 +275,7 @@ The ``README.md`` file will contain instructions on the order that each script s +--------------------+----------------------------+------------+-----------+ | ufs-weather-model | ./run_fcst.sh | 6 | 1h 40 m | +--------------------+----------------------------+------------+-----------+ - | UPP | ./run_post.sh | 1 | 7 m | + | EMC_post | ./run_post.sh | 1 | 7 m | +--------------------+----------------------------+------------+-----------+ This needs to stay UPP. ------------------------------ In docs/UsersGuide/source/CodeReposAndDirs.rst <[#209 (comment)](https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800964100)> : > @@ -30,14 +30,14 @@ repositories associated with this umbrella repo (see :numref:`Table %s <top_leve | Repository for | https://github.com/ufs-community/ufs-weather-model | This file shouldn't change, as it was updated recently to account for the new GitHub organization used for regional_workflow and the name change for UPP. ------------------------------ In docs/UsersGuide/source/ConfigParameters.inc <[#209 (comment)](https://github.com/ufs-community/ufs-srweather-app/pull/209#discussion_r800965036)> : > @@ -310,7 +310,7 @@ Maximum number of attempts. Customized Post Configuration Parameters ======================================== ``USE_CUSTOM_POST_CONFIG_FILE``: (Default: “FALSE”) - Flag that determines whether a user-provided custom configuration file should be used for post-processing the model data. If this is set to "TRUE", then the workflow will use the custom post-processing (UPP) configuration file specified in ``CUSTOM_POST_CONFIG_FP``. Otherwise, a default configuration file provided in the UPP repository will be used. + Flag that determines whether a user-provided custom configuration file should be used for post-processing the model data. If this is set to "TRUE", then the workflow will use the custom post-processing (UPP) configuration file specified in ``CUSTOM_POST_CONFIG_FP``. Otherwise, a default configuration file provided in the EMC_post repository will be used. ``CUSTOM_POST_CONFIG_FP``: (Default: “”) The full path to the custom post flat file, including filename, to be used for post-processing. This is only used if ``CUSTOM_POST_CONFIG_FILE`` is set to "TRUE". This file shouldn't change (needs to stay as "UPP"). — Reply to this email directly, view it on GitHub <[#209 (review)](https://github.com/ufs-community/ufs-srweather-app/pull/209#pullrequestreview-875116323)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AXDGAEYWHDZ7Y4XCTKPKIK3U2AJFHANCNFSM5NYFG4TA> . Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. You are receiving this because you authored the thread.Message ID: ***@***.***>

Thanks, Gillian!  Looking forward to getting this incorporated into the repo.  Thank you for your work on the documentation!

2022-02-08 17:50 UTC, JeffBeck-NOAA commented on docs/UsersGuide/source/InputOutputFiles.rst
Want to keep this UPP, thanks!

2022-02-08 19:21 UTC, mkavulich commented on docs/UsersGuide/source/InputOutputFiles.rst
> +located in ``ufs-srweather-app/src/EMC_post/parm``.
FYI the official name is now UPP, EMC_post was used for the last release

2022-02-11 18:58 UTC, closed without merging