Add support on NSSL/Odin
ufs-community/ufs-srweather-app pull request #227
Opened 2022-03-22 20:17 UTC by ywangwof

## DESCRIPTION OF CHANGES: 
Add support on Odin using Intel 2020 and HPC-stack modules.

## TESTS CONDUCTED: 
Tested on Odin at NSSL.

## DEPENDENCIES:
None

## DOCUMENTATION:
It follows the same standard as on Jet/hera etc. Just changed the platform name to "_odin_".

## NEW FILES:
Just one new file.
- _env/build_odin_intel.env_

2022-03-22 22:04 UTC, JeffBeck-NOAA commented
@ywangwof, I didn't see any updates to the detect_machine.sh script or a workflow environment file.  Would it be possible to add those changes to this PR?

2022-03-22 22:24 UTC, ywangwof commented
Thanks for the suggestion. The files were added.

2022-03-22 22:26 UTC, JeffBeck-NOAA requested changes

2022-03-22 22:26 UTC, JeffBeck-NOAA commented on env/detect_machine.sh
>  esac
@ywangwof, could you change the comment here to reflect the login node name (or names) for Odin?  Thanks!

2022-03-22 22:26 UTC, JeffBeck-NOAA commented
> Thanks for the suggestion. The files were added.

Thanks, @ywangwof!

2022-03-22 22:27 UTC, JeffBeck-NOAA commented on env/detect_machine.sh
>  esac
Also, based on the structure for other machines, I think it's best to be explicit and list all nid0 values, instead of the wildcard.  Thanks!

2022-03-22 22:34 UTC, ywangwof commented
Updated _detect_machine.sh_ to follow the standards on other machines. Thanks.

2022-03-22 23:15 UTC, JeffBeck-NOAA approved these changes

2022-03-23 00:52 UTC, chan-hoo approved these changes

2022-03-23 01:00 UTC, merged