[develop] Add build_hera_gnu.lua modulefile.
ufs-community/ufs-srweather-app pull request #477
Opened 2022-11-14 21:33 UTC by MichaelLueken

## DESCRIPTION OF CHANGES: 
Currently, the only machine that has a functioning GNU modulefile is Cheyenne.  It has been noted that several developers don't have access to Cheyenne, so if there are issues with GNU compilers, it is difficult, if not impossible, to debug.  All of the necessary libraries are available on Hera to compile the SRW App using `GNU 9.2.0` with `MPICH 3.3.2`.  A new `build_hera_gnu.lua` modulefile has been created so that developers who can't access Cheyenne are still able to test their changes on another machine using the GNU compiler.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- [X] hera.gnu
The SRW App successfully compiled on Hera using GNU 9.2.0.  Running fundamental tests currently.
- [ ] fundamental test suite

## ISSUE: 
Completes #476 

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2022-11-14 21:49 UTC, venitahagerty commented
Machine: hera
Compiler: gnu
Job: build
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1122018556/20221114213516/ufs-srweather-app
Build was Successful
If test failed, please make changes and add the following label back:
ci-hera-gnu-build

2022-11-14 21:52 UTC, danielabdi-noaa commented on modulefiles/build_hera_gnu.lua
> +setenv("CMAKE_Fortran_COMPILER","mpiifort")
These should be the GNU couterparts i think
```Lua
setenv("CMAKE_C_COMPILER","mpicc")
setenv("CMAKE_CXX_COMPILER","mpicxx")
setenv("CMAKE_Fortran_COMPILER","mpif90")
```

2022-11-14 22:27 UTC, MichaelLueken commented
@danielabdi-noaa Nice catch!  I have corrected this entries.

2022-11-14 22:50 UTC, venitahagerty commented
Machine: hera
Compiler: gnu
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1122018556/20221114223509/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-gnu-WE

2022-11-15 01:03 UTC, danielabdi-noaa approved these changes

2022-11-15 11:45 UTC, natalie-perlin requested changes
New hpc-stack location in EPIC-managed space. As discussed in https://github.com/ufs-community/ufs-srweather-app/pull/419, https://github.com/ufs-community/ufs-srweather-app/issues/427, https://github.com/ufs-community/ufs-weather-model/issues/1465, https://github.com/ufs-community/ufs-weather-model/pull/1468.
This stack in this location on Hera has been independently tested with the UFS-WM by @jkbk2004, and not changing the baseline.

2022-11-15 11:45 UTC, natalie-perlin commented on modulefiles/build_hera_gnu.lua
> +
New hpc-stack location in EPIC-managed space. As discussed in [SRW-PR-419](https://github.com/ufs-community/ufs-srweather-app/pull/419), [SRW-Issue-427](https://github.com/ufs-community/ufs-srweather-app/issues/427), [UFS-WM-Issue-1465](https://github.com/ufs-community/ufs-weather-model/issues/1465), [UFS-WM-PR-1468](https://github.com/ufs-community/ufs-weather-model/pull/1468).
This stack in this location on Hera has been independently tested with the UFS-WM by @jkbk2004, and not changing the baseline. The following lines 13-16 would be changed to the following:

```
gnu_ver=os.getenv("gnu_ver") or "9.2.0"
load(pathJoin("gnu", gnu_ver))

prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2/modulefiles/stack")

load(pathJoin("hpc", os.getenv("hpc_ver") or "1.2.0"))
load(pathJoin("hpc-gnu", os.getenv("hpc-gnu_ver") or "9.2"))
```

2022-11-15 11:45 UTC, natalie-perlin commented on modulefiles/build_hera_gnu.lua
> +load(pathJoin("nccmp", os.getenv("nccmp_ver") or "1.8.7"))
The version built with the new stack: 1.8.9 (or 1.9.1)
`load(pathJoin("nccmp", os.getenv("nccmp_ver") or "1.8.9"))`

2022-11-15 13:02 UTC, natalie-perlin commented
A test with EPIC-managed stack is successfully running on Hera (SRW built, all the pre-processing tasks completed, forecast is running, postprocessing is running)

Test directory: /scratch1/NCEPDEV/nems/role.epic/sandbox/SRW/expt_dirs/test_gnu/grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16

2022-11-15 16:17 UTC, MichaelLueken commented
@natalie-perlin Thank you very much for your review!  I have made the suggested changes so that the Hera GNU modulefile will use the new EPIC maintained HPC-stack location.

2022-11-15 16:35 UTC, venitahagerty commented
Machine: hera
Compiler: gnu
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1122018556/20221115162014/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-gnu-WE

2022-11-15 16:50 UTC, danielabdi-noaa commented
@MichaelLueken I don't think the GNU github actions labels work on either Hera or Jet. We will need to communicate with @venitahagerty  to pass compiler options for `setup_WE2E_tests.sh`.
```
./setup_WE2E_tests.sh machine account compiler test_type
```
In the past it used only the first two, and i don't think it has been updated to use the others.

2022-11-15 17:01 UTC, MichaelLueken commented
@danielabdi-noaa Thanks for the heads up!  Looking at the output from the github actions label, I see that it is being built using Intel rather than GNU.

@venitahagerty How difficult is it to update the github actions so that the test will run using:

`./setup_WE2E_tests.sh machine account compiler test_type`

This way, we will be able to test both the Intel and GNU compilers on Hera moving forward.

2022-11-16 18:13 UTC, MichaelLueken commented
@natalie-perlin I see that the changes in ufs-weather-model PR [#1468](https://github.com/ufs-community/ufs-weather-model/pull/1468) have been merged.  Would you like for me to update the Hera Intel modulefile to point to the new EPIC-maintained HPC-stack location as part of this PR as well?

2022-11-16 18:38 UTC, MichaelLueken commented
On a similar note, @danielabdi-noaa, would you like for me to merge your PR #479 work into this PR?  This way, all modulefile and testing modifications for Hera can be completed with this single PR.

2022-11-16 18:47 UTC, danielabdi-noaa commented
@MichaelLueken Sure, please go ahead and merge them.

2022-11-16 21:23 UTC, MichaelLueken commented
@natalie-perlin I have updated both the `build_hera_intel.lua` and `build_hera_gnu.lua` to use the EPIC-maintained HPC-stack locations.  The fundament WE2E tests have been run for both GNU and Intel and they both successfully passed. 
 Please let me know if there are any issues that you see with these two files.

@danielabdi-noaa I have merged your work from PR #479 into this PR.  If there are any additional changes that you would like to see, please let me know.

2022-11-16 22:13 UTC, natalie-perlin approved these changes
Thank you for the changes, approving!

2022-11-17 14:27 UTC, merged