Update README documentation from release branch
ufs-community/ufs-srweather-app pull request #62
Opened 2020-11-24 04:59 UTC by mkavulich

## DESCRIPTION OF CHANGES: 
Bring over README documentation from release branch since it is now sourced by the develop branch of regional_workflow (since commit https://github.com/NOAA-EMC/regional_workflow/commit/0711f0eb6d9ac51a946fe4cc9814795abb63b951). Therefore these files are needed for continued development on the regional_workflow repository from develop.

## TESTS CONDUCTED: 
None yet.

## ISSUE (optional): 
Partially resolves #57

2020-11-24 05:01 UTC, mkavulich commented
I'm aware that ideally this issue would be resolved by cherry-picking all needed commits from the release branch, but that would require extensive testing due to various changes made in the interim, and this needs to be fixed urgently for further development purposes.

2020-11-24 15:07 UTC, christinaholtNOAA requested changes
My tests on Jet are failing on the build. l will need some additional help with this test.

So far, I have tried to point to the develop branch of ufs-weather-model after failures due to a severely reduced set of CCPP packages in the release branch. And am now failing with issues seemingly related to inline post. Will follow up in person....

2020-11-24 15:21 UTC, christinaholtNOAA commented on docs/INSTALL
> +
Well, this was me being dumb...please disregard.

2020-11-24 15:37 UTC, JulieSchramm approved these changes

2020-11-24 21:37 UTC, JeffBeck-NOAA commented
@mkavulich @christinaholtNOAA @gsketefian, the default Externals.cfg for the develop branch of ufs-srweather-app needs to be changed to grab the develop branch of ufs-weather-model, not release/public-v2.  My first build error was related to missing CCPP suites.  @mkavulich, would you mind making that switch and pushing it to this PR?  Now, I'm getting the following when building ufs-weather-model:

/lfs4/BMC/wrfruc/beck/ufs-srweather-app_Mike/src/ufs_weather_model/FV3/fv3_cap.F90(1157): error #6632: Keyword arguments are invalid with
         call ESMF_VMEpochEnter(epoch=ESMF_VMEpoch_Buffer, rc=rc)
--------------------------------^

2020-11-24 21:45 UTC, christinaholtNOAA commented
@JeffBeck-NOAA The top of develop does not work, either.

2020-11-24 22:36 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA The top of develop does not work, either.

Yes, the modules in the README files are currently based off the release branches for all repositories.  A set of develop branch repo hashes (could be the HEAD for all) will need to be defined in the Externals.cfg file, along with a set of compatible modules for those branches in the README files.  Once that is set up, then the compile should work.

2020-12-02 00:27 UTC, mkavulich commented
Since this quick fix turned out to be a dead end, I am closing this PR to open a new, better one merging commits from the release branch (to go in after #63)

2020-12-02 00:27 UTC, closed without merging