[develop] Add raddar reflectivity task.
ufs-community/ufs-srweather-app pull request #638
Opened 2023-03-06 21:20 UTC by danielabdi-noaa

## DESCRIPTION OF CHANGES: 

Add `process_radarref` task from `RRFS_dev1`.
Note that there is no workflow so this PR can not be run independently until then.
However, it did successfully run for both spinup/production cycles in PR #540.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [X] hera.intel
  The CONUS 3km test case run successfully with this task in PR #540 
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:

## DOCUMENTATION:

## ISSUE: 

- #489 

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

## CONTRIBUTORS (optional):

2023-03-22 19:36 UTC, panll approved these changes
Tested on Hera. It works fine.

2023-03-22 21:49 UTC, EdwardSnyder-NOAA commented on jobs/JREGIONAL_PROCESS_BUFR
> +#!/bin/bash
Looks like the BUFR jobs script was added instead of the Radar Ref.

2023-03-22 22:01 UTC, danielabdi-noaa commented on jobs/JREGIONAL_PROCESS_BUFR
> +#!/bin/bash
Thank a lot, I have replaced the j-job with the right one!

2023-03-23 23:11 UTC, christinaholtNOAA requested changes
I left several suggestions for clean up below, but we definitely need to make sure that we aren't pointing to unsupported data paths before merging.

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +#YYYYMMDD=${YYYYMMDDHH:0:8}
Please remove commented code here and for gridspec_dir above.

2023-03-23 23:11 UTC, christinaholtNOAA commented on jobs/JREGIONAL_PROCESS_RADARREF
> +#
Please add the required environment variables coming from Rocoto in the description here.

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +    for cyc_start in "${CYCL_HRS_SPINSTART[@]}"; do
It would be more efficient here and below to just check to see if ${HH} is contained in the array. For example:

```

if [[ ${CYCL_HRS_SPINSTART[@]} =~ "$HH" ]] ; then
  BKTYPE=1
fi
```

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +      done
Removing the random large white space in the cp_vrfy statements is preferable. Also, this is the only use of list_iolayout, so making the computation closer to where it's used is easier to understand. It's potentially cleaner to go with:

```
for iii in $(seq -w 0 $(printf %4.4i $n_iolayouty))
do 
  cp_vrfy ....
done
```

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +esac
We do want to make sure that all the machine case statements are removed from the scripts.

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +  if [ -s filelist_mrms ]; then
Perhaps this could just be an else?

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +for bigmin in ${RADARREFL_TIMELEVEL[@]}; do
bigmin is very difficult to understand from a readability perspective. Maybe the variable name `timelevel` would be clearer given the description of that variable? At least them we can recall that we're looping through the RADARREFL_TIMELEVEL list.

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +  for min in ${RADARREFL_MINS[@]}
Maybe add a comment here that this internal loop is looking for files within close proximity to the time level in question?

2023-03-23 23:11 UTC, christinaholtNOAA commented on scripts/exregional_process_radarref.sh
> +      ss=$(printf %2.2i ${s})
Perhaps `sec` or `second` here to be consistent with `min`? It's hard to visually pick out individial s's in this chunk of code.

2023-03-23 23:11 UTC, christinaholtNOAA commented on ush/machine/jet.yaml
> +  DOMAIN_PREGEN_BASEDIR: /mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/FV3LAM_pregen
Do we want to make this change? We need to keep the paths pointing to where the EPIC-supported data for SRW lives and ensure that's populated with the right data.

2023-03-23 23:11 UTC, christinaholtNOAA commented on ush/machine/jet.yaml
> +  OBSPATH_NSSLMOSIAC: /mnt/lfs4/BMC/wrfruc/Ruifang.Li/data/reflectivity
We definitely do not want this path to be a SRW community dependency.

2023-03-24 16:09 UTC, EdwardSnyder-NOAA commented on ush/machine/jet.yaml
> +  DOMAIN_PREGEN_BASEDIR: /mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/FV3LAM_pregen
@christinaholtNOAA - [PR 674](https://github.com/ufs-community/ufs-srweather-app/pull/674) switches the UFS_SRW_App paths to EPIC locations from the SRW role account locations. We've done testing to ensure experiments ran successfully.

2023-03-27 23:07 UTC, christinaholtNOAA reviewed
One more tiny change request, but the changes look good. 

It looks like the supported radar obs paths are here:

Jet: /public/data/radar/mrms
Hera: /scratch2/BMC/public/data/radar/nssl/mrms/conus

@mkavulich Might find this useful for his work with data retrieval, too.

2023-03-27 23:07 UTC, christinaholtNOAA commented on ush/config_defaults.yaml
> +  #   machine specific grib2 file name extension (grib2 or grib2.gz)
This should probably be `OBS_SUFFIX`.

2023-03-27 23:31 UTC, danielabdi-noaa commented
> One more tiny change request, but the changes look good.
> 
> It looks like the supported radar obs paths are here:
> 
> Jet: /public/data/radar/mrms Hera: /scratch2/BMC/public/data/radar/nssl/mrms/conus
> 
> @mkavulich Might find this useful for his work with data retrieval, too.

@christinaholtNOAA  Note that those are paths for realtime forecasts only. You can find the full list of observation paths for realtime/retro runs in this commit for hera/jet/wcoss2: [obs data paths](https://github.com/ufs-community/ufs-srweather-app/pull/647/commits/db8524fb80d421000f8723eb791c90396909d3c8)

2023-04-10 20:24 UTC, christinaholtNOAA approved these changes
LGTM.

2023-04-11 22:31 UTC, christinaholtNOAA commented
@MichaelLueken In our RRFS dev merge discussion yesterday we chatted about pushing this one through when it's ready. If we can go ahead with that, it would be helpful. Thanks!

2023-04-14 14:50 UTC, MichaelLueken commented
@danielabdi-noaa I'm working on reviewing and testing this PR now.  It looks like there is a conflict in `ush/config_defaults.yaml`.  Please merge develop into your `feature/task_radarref` branch one more time and I will approve this work and kick off the Jenkins tests.  Thanks!

2023-04-14 15:37 UTC, danielabdi-noaa commented
@MichaelLueken I have resolved the conflicts. You can kick off the Jenkins tests now.

2023-04-14 16:13 UTC, MichaelLueken approved these changes
@danielabdi-noaa These changes look good to me!  The necessary components to run this task and the process bufr task will be completed in PR #725.  Approving now.

2023-04-14 19:30 UTC, MichaelLueken commented
The Jenkins tests have completed.  The Hera Intel tests failed.  Manually running them, all tests successfully passed (with the exception of `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR`, which failed due to issue #688).  Moving forward with merging this work now.

2023-04-14 19:30 UTC, merged